services:
  nginx:
    container_name: nginx
    depends_on:
      - wordpress
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    volumes:
      - wordpress_vol:/var/www/html
    networks:
      - inception
    restart: on-failure
    ports:
      - "443:443"

  wordpress:
    container_name: wordpress
    depends_on:
      - mariadb
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - wordpress_vol:/var/www/html
    networks:
      - inception
    restart: on-failure
    expose:
      - 9000

  mariadb:
    container_name: mariadb
    image: mariadb
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
      args:
        - ADMIN_USER=${ADMIN_USER}
        - ADMIN_PWD=${ADMIN_PWD}
        - DATABASE_NAME=${DATABASE_NAME}
    environment:
      - ADMIN_USER
      - ADMIN_PWD
      - DATABASE_NAME
    env_file:
      - .env
    volumes:
      - mariadb_vol:/var/lib/mysql
    networks:
      - inception
    restart: on-failure
    expose:
      - 3306

volumes:
  wordpress_vol:
    driver: local
    driver_opts:
      type: none
      device: /home/lsabatie/data/wordpress
      o: bind
  mariadb_vol:
    driver: local
    driver_opts:
      type: none
      device: /home/lsabatie/data/mariadb
      o: bind

networks:
  inception:
    driver: bridge