services:
  nginx:
    container_name: nginx
    image: nginx
    depends_on:
      - wordpress
      - mariadb
    build:
      context: ./requirements/nginx
    volumes:
      - wordpress_vol:/var/www/html/
    networks:
      - inception
    restart: on-failure
    extra_hosts:
      - "www.lsabatie.42.fr:0.0.0.0"
      - "lsabatie.42.fr:0.0.0.0"
    ports:
      - "443:443"

  wordpress:
    container_name: wordpress
    image : wordpress
    depends_on:
      - mariadb
    build:
      context: ./requirements/wordpress
    env_file:
      - .env
    volumes:
      - wordpress_vol:/var/www/html/
    networks:
      - inception
    restart: on-failure
    extra_hosts:
      - "www.lsabatie.42.fr:0.0.0.0"
      - "lsabatie.42.fr:0.0.0.0"
    expose:
      - 9000

  mariadb:
    container_name: mariadb
    image: mariadb
    build:
      context: ./requirements/mariadb
    env_file:
      - .env
    volumes:
      - mariadb_vol:/var/lib/mysql
    networks:
      - inception
    restart: on-failure
    extra_hosts:
      - "www.lsabatie.42.fr:0.0.0.0"
      - "lsabatie.42.fr:0.0.0.0"
    expose:
      - 3306

volumes:
  wordpress_vol:
    driver: local
    driver_opts:
      type: none
      device: /home/lsabatie/data/wordpress_vol
      o: bind
  mariadb_vol:
    driver: local
    driver_opts:
      type: none
      device: /home/lsabatie/data/mariadb_vol
      o: bind

networks:
  inception:
    name: inception
    driver: bridge